[package]
name = "rpifan3"
version = "0.1.0"
authors = ["Ben Stonebraker <thatfleppicguy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
serde_json = "1.0.62"

